liferay:
  build: .
  container_name: liferay
  net: testnet
  ports:
  - 2009:8080

liferay-mysql:
  container_name: liferay-mysql
  restart: always
  image: mysql:5.6.25
  net: testnet
  expose:
    - "3306"
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: liferay
    MYSQL_PASSWORD: liferay
    MYSQL_DATABASE: lportal
