liferay:
    #  build: .
  build: build/layer_3_configurations
  container_name: liferay
  net: testnet
  ports:
  - 2009:8080
  environment:
    REMOTE_DB_ENABLE: "true"
    REMOTE_ES_ENABLE: "false"
    INITIAL_SETUP_ENABLE: "true"
    PORTAL_EXT_SETUP_ENABLE: "true"


liferay-mysql:
  container_name: liferay-mysql
  restart: always
  image: mysql:5.6.25
  net: testnet
  expose:
    - "3306"
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: liferay
    MYSQL_PASSWORD: liferay
    MYSQL_DATABASE: lportal

#elasticsearch:
#  container_name: elasticsearch
#  restart: always
  #  image: elasticsearch:2.1.1
  #  net: testnet
  #  command: elasticsearch -Des.network.host=0.0.0.0
  #  ports:
      #    - "9200:9200"
      #  volumes:
      #    - elasticsearch_data:/usr/share/elasticsearch/data
